=== asterisk/asterisk/doc/appdocsxml.dtd
<!ELEMENT docs (module|application|function|agi|manager|managerEvent|info|configInfo)*>
  <!ATTLIST docs xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude">

  <!ELEMENT xi:include (xi:fallback?) >
  <!ATTLIST xi:include
  xmlns:xi	CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
  href		CDATA       #IMPLIED
  parse		(xml|text)  "xml"
  xpointer	CDATA       #IMPLIED
  encoding	CDATA       #IMPLIED
  accept	CDATA       #IMPLIED
  accept-language CDATA  #IMPLIED >

  <!ELEMENT module (depend*,use*,conflict*,defaultenabled?,support_level?,replacement?,deprecated_in?,removed_in?)>
  <!ATTLIST module name CDATA #REQUIRED>
  <!ATTLIST module language CDATA #REQUIRED>

  <!ELEMENT support_level (#PCDATA)>

  <!ELEMENT depend (#PCDATA)>
  <!ATTLIST depend type CDATA #IMPLIED>

  <!ELEMENT defaultenabled (#PCDATA)>

  <!ELEMENT replacement (#PCDATA)>

  <!ELEMENT use (#PCDATA)>
  <!ATTLIST use type CDATA #IMPLIED>

  <!ELEMENT conflict (#PCDATA)>

  <!ELEMENT deprecated_in (#PCDATA)>

  <!ELEMENT removed_in (#PCDATA)>

  <!ELEMENT application (since?,synopsis?,syntax?,description?,see-also?)>
  <!ATTLIST application name CDATA #REQUIRED>
  <!ATTLIST application language CDATA #REQUIRED>
  <!ATTLIST application module CDATA #IMPLIED>

  <!ELEMENT function (since?,synopsis?,syntax?,description?,see-also?)>
  <!ATTLIST function name CDATA #REQUIRED>
  <!ATTLIST function language CDATA #REQUIRED>
  <!ATTLIST function module CDATA #IMPLIED>

  <!ELEMENT agi (since?,synopsis?,syntax?,description?,see-also?)>
  <!ATTLIST agi name CDATA #REQUIRED>
  <!ATTLIST agi language CDATA #REQUIRED>
  <!ATTLIST agi module CDATA #IMPLIED>

  <!ELEMENT manager (since?,synopsis?,syntax?,description?,see-also?,responses?)>
  <!ATTLIST manager name CDATA #REQUIRED>
  <!ATTLIST manager language CDATA #REQUIRED>
  <!ATTLIST manager module CDATA #IMPLIED>

  <!ELEMENT responses (list-elements?,(managerEvent|xi:include))>

  <!ELEMENT list-elements (managerEvent+|xi:include+)>

  <!ELEMENT managerEvent (managerEventInstance+)>
  <!ATTLIST managerEvent name CDATA #REQUIRED>
  <!ATTLIST managerEvent language CDATA #REQUIRED>
  <!ATTLIST managerEvent module CDATA #IMPLIED>

  <!ELEMENT managerEventInstance (since?,synopsis?,syntax?,description?,see-also?)*>
  <!ATTLIST managerEventInstance class CDATA #REQUIRED>
  <!ATTLIST managerEventInstance module CDATA #IMPLIED>

  <!ELEMENT configInfo (synopsis?,description?,configFile+)>
  <!ATTLIST configInfo name CDATA #REQUIRED>
  <!ATTLIST configInfo language CDATA #REQUIRED>

  <!ELEMENT configFile (configObject|xi:include)+>
  <!ATTLIST configFile name CDATA #REQUIRED>

  <!ELEMENT configObject (since?|synopsis?|description?|syntax?|see-also?|(configOption|xi:include))*>
  <!ATTLIST configObject name CDATA #REQUIRED>

  <!ELEMENT configOption (since?,synopsis,description?,syntax?,see-also?)*>
  <!ATTLIST configOption name CDATA #REQUIRED>
  <!ATTLIST configOption regex (yes|no|true|false) "false">
  <!ATTLIST configOption default CDATA #IMPLIED>
  <!ATTLIST configOption type CDATA #IMPLIED>

  <!ELEMENT matchInfo (category,field?)>

  <!ELEMENT dataType (#PCDATA)>

  <!ELEMENT category (#PCDATA)>
  <!ATTLIST category match (yes|no|true|false) #REQUIRED>

  <!ELEMENT field (#PCDATA)>
  <!ATTLIST field name CDATA #REQUIRED>

  <!ELEMENT info (para|example|note|warning|variablelist|enumlist|info|xi:include)*>
  <!ATTLIST info name CDATA #REQUIRED>
  <!ATTLIST info language CDATA #REQUIRED>
  <!ATTLIST info tech CDATA #REQUIRED>
  <!ATTLIST info module CDATA #IMPLIED>

  <!ELEMENT see-also (ref|xi:include)*>

  <!ELEMENT ref (#PCDATA)>
  <!ATTLIST ref type (application|function|astcli|link|manpage|filename|agi|manager|managerEvent|configOption) #REQUIRED>
  <!ATTLIST ref module CDATA #IMPLIED>

  <!ELEMENT since (version+)>

  <!ELEMENT version (#PCDATA)>

  <!ELEMENT synopsis (#PCDATA)>

  <!ELEMENT syntax (parameter|dataType|category|matchInfo|xi:include|channel_snapshot|bridge_snapshot)*>
  <!ATTLIST syntax argsep CDATA ",">

  <!ELEMENT channel_snapshot (#PCDATA)>
  <!ATTLIST channel_snapshot prefix CDATA "">

  <!ELEMENT bridge_snapshot (#PCDATA)>
  <!ATTLIST bridge_snapshot prefix CDATA "">

  <!ELEMENT configOptionToEnum (configOption|xi:include)*>
  <!ATTLIST configOptionToEnum prefix CDATA "">

  <!ELEMENT description (para|note|warning|variablelist|enumlist|info|example|xi:include)*>

  <!ELEMENT parameter (optionlist|enumlist|argument|para|note|warning|parameter|info|documentationtype|xi:include)*>
  <!ATTLIST parameter name CDATA "">
  <!ATTLIST parameter required (yes|no|true|false) "false">
  <!ATTLIST parameter multiple (yes|no|true|false) "false">
  <!ATTLIST parameter hasparams (yes|no|true|false|optional) "false">
  <!ATTLIST parameter literal (yes|no|true|false) "false">
  <!ATTLIST parameter default CDATA "">
  <!ATTLIST parameter argsep CDATA ",">
  <!ATTLIST parameter documentationtype CDATA "">

  <!ELEMENT optionlist (option+)>
  <!ELEMENT option (argument|para|note|warning|variablelist|enumlist|info|xi:include)*>
  <!ATTLIST option name CDATA #REQUIRED>
  <!ATTLIST option argsep CDATA ",">
  <!ATTLIST option implies CDATA "">
  <!ATTLIST option hasparams CDATA "">

  <!ELEMENT enumlist (configOptionToEnum|enum)+>
  <!ELEMENT enum (para|note|warning|parameter|enumlist|info|xi:include)*>
  <!ATTLIST enum name CDATA "">

  <!ELEMENT argument (para|note|warning|variablelist|argument|info|xi:include)*>
  <!ATTLIST argument name CDATA #REQUIRED>
  <!ATTLIST argument multiple (yes|no|true|false) "false">
  <!ATTLIST argument required (yes|no|true|false) "false">
  <!ATTLIST argument hasparams (yes|no|true|false|optional) "false">
  <!ATTLIST argument argsep CDATA ",">

  <!ELEMENT para (#PCDATA|astcli|literal|emphasis|filename|directory|replaceable|variable|xi:include)*>
  <!ELEMENT literal (#PCDATA)>
  <!ELEMENT emphasis (#PCDATA)>
  <!ELEMENT filename (#PCDATA)>
  <!ELEMENT replaceable (#PCDATA)>
  <!ELEMENT directory (#PCDATA)>
  <!ELEMENT astcli (#PCDATA)>

  <!ELEMENT example (#PCDATA|xi:include)*>
  <!ATTLIST example title CDATA "">
  <!ATTLIST example language CDATA "" >

  <!ELEMENT note (para+|xi:include*)>
  <!ELEMENT warning (para+|xi:include*)>

  <!ELEMENT variablelist (variable+|xi:include*)>
  <!ELEMENT variable (#PCDATA|value|para|info|xi:include)*>
  <!ATTLIST variable name CDATA "">

  <!ELEMENT value (#PCDATA)>
  <!ATTLIST value name CDATA #REQUIRED>
  <!ATTLIST value default CDATA "">

=== asterisk/asterisk/res/ari/ari_doc.xml
<!DOCTYPE docs SYSTEM "appdocsxml.dtd">
<?xml-stylesheet type="text/xsl" href="appdocsxml.xslt"?>
<docs xmlns:xi="http://www.w3.org/2001/XInclude">
	<configInfo name="res_ari" language="en_US">
		<synopsis>HTTP binding for the Stasis API</synopsis>
		<configFile name="ari.conf">
			<configObject name="general">
				<since>
					<version>12.0.0</version>
				</since>
				<synopsis>General configuration settings</synopsis>
				<configOption name="enabled">
					<since>
						<version>12.0.0</version>
					</since>
					<synopsis>Enable/disable the ARI module</synopsis>
					<description>
						<para>This option enables or disables the ARI module.</para>
						<note>
							<para>ARI uses Asterisk's HTTP server, which must also be enabled in <filename>http.conf</filename>.</para>
						</note>
					</description>
					<see-also>
						<ref type="filename">http.conf</ref>
						<ref type="link">https://docs.asterisk.org/Configuration/Core-Configuration/Asterisk-Builtin-mini-HTTP-Server/</ref>
					</see-also>
				</configOption>
				<configOption name="websocket_write_timeout" default="100">
					<since>
						<version>11.11.0</version>
						<version>12.4.0</version>
					</since>
					<synopsis>Write timeout (ms).</synopsis>
					<description>
						<para>
							The maximum number of milliseconds to wait for a write
							to the WebSocket to succeed. The WebSocket will be closed
							when the timeout is reached.  For outgoing WebSocket connections,
							this sets the default timeout which can be overridden in websocket_client.conf.
						</para>
						<note>
							<para>
							Success means the write request was accepted by the
							operating system and does not imply the payload was
							actually transmitted or received by the server.
							</para>
						</note>
					</description>
					<see-also>
						<ref type="configOption" module="res_websocket_client">write_timeout</ref>
					</see-also>
				</configOption>
				<configOption name="pretty">
					<since>
						<version>12.0.0</version>
					</since>
					<synopsis>Responses from ARI are formatted to be human readable</synopsis>
				</configOption>
				<configOption name="auth_realm">
					<since>
						<version>12.0.0</version>
					</since>
					<synopsis>Realm to use for authentication. Defaults to Asterisk REST Interface.</synopsis>
				</configOption>
				<configOption name="allowed_origins">
					<since>
						<version>12.0.0</version>
					</since>
					<synopsis>Comma separated list of allowed origins, for Cross-Origin Resource Sharing. May be set to * to allow all origins.</synopsis>
				</configOption>
				<configOption name="channelvars">
					<since>
						<version>14.2.0</version>
					</since>
					<synopsis>Comma separated list of channel variables to display in channel json.</synopsis>
				</configOption>
			</configObject>

			<configObject name="user">
				<since>
					<version>12.0.0</version>
				</since>
				<synopsis>Per-user configuration settings</synopsis>
				<configOption name="type">
					<since>
						<version>13.30.0</version>
						<version>16.7.0</version>
						<version>17.1.0</version>
					</since>
					<synopsis>Define this configuration section as a user.</synopsis>
					<description>
						<enumlist>
							<enum name="user"><para>Configure this section as a <replaceable>user</replaceable></para></enum>
						</enumlist>
					</description>
				</configOption>
				<configOption name="read_only">
					<since>
						<version>13.30.0</version>
						<version>16.7.0</version>
						<version>17.1.0</version>
					</since>
					<synopsis>When set to yes, user is only authorized for read-only requests</synopsis>
				</configOption>
				<configOption name="password">
					<since>
						<version>13.30.0</version>
						<version>16.7.0</version>
						<version>17.1.0</version>
					</since>
					<synopsis>Crypted or plaintext password (see password_format)</synopsis>
				</configOption>
				<configOption name="password_format">
					<since>
						<version>12.0.0</version>
					</since>
					<synopsis>password_format may be set to plain (the default) or crypt. When set to crypt, crypt(3) is used to validate the password. A crypted password can be generated using mkpasswd -m sha-512. When set to plain, the password is in plaintext</synopsis>
				</configOption>
				<configOption name="acl">
					<since>
						<version>20.19.0</version>
						<version>22.9.0</version>
						<version>23.3.0</version>
					</since>
					<synopsis>List of IP ACL section names in acl.conf</synopsis>
					<description><para>
						This matches sections configured in <literal>acl.conf</literal>.
					</para></description>
				</configOption>
				<configOption name="deny">
					<since>
						<version>20.19.0</version>
						<version>22.9.0</version>
						<version>23.3.0</version>
					</since>
					<synopsis>List of IP addresses to deny access from</synopsis>
					<description><para>
						The value is a comma-delimited list of IP addresses. IP addresses may
						have a subnet mask appended. The subnet mask may be written in either
						CIDR or dotted-decimal notation. Separate the IP address and subnet
						mask with a slash ('/')
					</para></description>
				</configOption>
				<configOption name="permit">
					<since>
						<version>20.19.0</version>
						<version>22.9.0</version>
						<version>23.3.0</version>
					</since>
					<synopsis>List of IP addresses to permit access from</synopsis>
					<description><para>
						The value is a comma-delimited list of IP addresses. IP addresses may
						have a subnet mask appended. The subnet mask may be written in either
						CIDR or dotted-decimal notation. Separate the IP address and subnet
						mask with a slash ('/')
					</para></description>
				</configOption>
			</configObject>
			<configObject name="outbound_websocket">
				<since>
					<version>20.15.0</version>
					<version>21.10.0</version>
					<version>22.5.0</version>
				</since>
				<synopsis>Outbound websocket configuration</synopsis>
				<configOption name="type">
					<since>
						<version>20.15.0</version>
						<version>21.10.0</version>
						<version>22.5.0</version>
					</since>
					<synopsis>Must be "outbound_websocket".</synopsis>
				</configOption>
				<configOption name="websocket_client_id">
					<since>
						<version>20.15.0</version>
						<version>21.10.0</version>
						<version>22.5.0</version>
					</since>
					<synopsis>The ID of a connection defined in websocket_client.conf.</synopsis>
				</configOption>
				<configOption name="apps">
					<since>
						<version>20.15.0</version>
						<version>21.10.0</version>
						<version>22.5.0</version>
					</since>
					<synopsis>Comma separated list of stasis applications that will use this websocket.</synopsis>
				</configOption>
				<configOption name="local_ari_user">
					<since>
						<version>20.15.0</version>
						<version>21.10.0</version>
						<version>22.5.0</version>
					</since>
					<synopsis>The local ARI user to act as.</synopsis>
				</configOption>
				<configOption name="subscribe_all" default="no">
					<since>
						<version>20.15.0</version>
						<version>21.10.0</version>
						<version>22.5.0</version>
					</since>
					<synopsis>Subscribe applications to all event</synopsis>
				</configOption>
			</configObject>
		</configFile>
	</configInfo>
</docs>

=== asterisk/asterisk/main/logger_doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE docs SYSTEM "appdocsxml.dtd">
<?xml-stylesheet type="text/xsl" href="appdocsxml.xslt"?>
<docs xmlns:xi="http://www.w3.org/2001/XInclude">
	<function name="LOG_GROUP" language="en_US">
		<synopsis>
			Set the channel group name for log filtering on this channel
		</synopsis>
		<syntax>
			<parameter name="group" required="false">
				<para>Channel log group name. Leave empty to remove any existing group membership.</para>
				<para>You can use any arbitrary alphanumeric name that can then be used by the
				"logger filter changroup" CLI command to filter dialplan output by group name.</para>
			</parameter>
		</syntax>
		<description>
			<para>Assign a channel to a group for log filtering.</para>
			<para>Because this application can result in dialplan execution logs
			being suppressed (or unsuppressed) from the CLI if filtering is active,
			it is recommended to call this as soon as possible when dialplan execution begins.</para>
			<para>Calling this multiple times will replace any previous group assignment.</para>
			<example title="Associate channel with group test">
			exten => s,1,Set(LOG_GROUP()=test)
				same => n,NoOp() ; if a logging call ID group filter name is enabled but test is not included, you will not see this
			</example>
			<example title="Associate channel with group important">
			exten => s,1,Set(LOG_GROUP()=important)
				same => n,Set(foo=bar) ; do some important things to show on the CLI (assuming it is filtered with important enabled)
				same => n,Set(LOG_GROUP()=) ; remove from group important to stop showing execution on the CLI
				same => n,Wait(5) ; do some unimportant stuff
			</example>
		</description>
		<see-also>
			<ref type="application">Log</ref>
		</see-also>
	</function>
</docs>

=== asterisk/asterisk/channels/chan_websocket_doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE docs SYSTEM "appdocsxml.dtd">
<docs xmlns:xi="http://www.w3.org/2001/XInclude">
	<configInfo name="chan_websocket" language="en_US">
		<synopsis>Configuration for chan_websocket</synopsis>
		<description><para>
			<emphasis>WebSocket Channel Driver</emphasis>
			</para>
		</description>
		<configFile name="chan_websocket.conf">
			<configObject name="global">
				<since>
					<version>20.18.0</version>
					<version>22.8.0</version>
					<version>23.2.0</version>
				</since>
				<synopsis>Global settings for chan_websocket</synopsis>
				<configOption name="control_message_format" default="plain-text">
					<since>
						<version>20.18.0</version>
						<version>22.8.0</version>
						<version>23.2.0</version>
					</since>
					<synopsis>Determines the format used for sending and receiving
					control mesages on the websocket.
					</synopsis>
					<description>
						<enumlist>
							<enum name="plain-text">
							<para>The legacy plain text single-line message format.</para>
							</enum>
							<enum name="json">
							<para>The new JSON format.</para>
							</enum>
						</enumlist>
					</description>
				</configOption>
				<configOption name="write_timeout" default="100">
					<since>
						<version>20.22.0</version>
						<version>22.12.0</version>
						<version>23.6.0</version>
						<version>24.0.0</version>
					</since>
					<synopsis>Write timeout (ms).</synopsis>
					<description>
						<para>
							The maximum number of milliseconds to wait for a write
							to the WebSocket to succeed. The WebSocket will be closed and the
							channel hung up when the timeout is reached.  For outgoing
							WebSocket connections, this sets the default timeout which can be
							overridden in websocket_client.conf.
						</para>
						<note>
							<para>
							Success means the write request was accepted by the
							operating system and does not imply the payload was
							actually transmitted or received by the server.
							</para>
						</note>
					</description>
					<see-also>
						<ref type="configOption" module="res_websocket_client">write_timeout</ref>
					</see-also>
				</configOption>
			</configObject>
		</configFile>
	</configInfo>

	<info name="Dial_Resource" language="en_US" tech="WebSocket">
		<para>WebSocket Dial Strings:</para>
		<para><literal>Dial(WebSocket/connectionid[/websocket_options])</literal></para>
		<para>WebSocket Parameters:</para>
		<enumlist>
			<enum name="connectionid">
				<para>For outgoing WebSockets, this is the ID of the connection
				in websocket_client.conf to use for the call.  To accept incoming
				WebSocket connections use the literal <literal>INCOMING</literal></para>
			</enum>
			<enum name="websocket_options">
				<para>Options to control how the WebSocket channel behaves.</para>
				<enumlist>
					<enum name="c(codec) - Specify the codec to use in the channel">
						<para></para>
						<para> If not specified, the first codec from the caller's channel will be used.
						</para>
					</enum>
					<enum name="d(media_direction) - Set the media direction for this call">
						<para>Sets the media direction for the call. It is important to
						note that this is from the perspective of the application, NOT
						Asterisk.</para>
						<enumlist>
						<enum name="both">
						<para>
						The default behavior. Media flows both ways like normal.
						</para>
						</enum>
						<enum name="in">
						<para>
						Asterisk will send media to the application but drop any media
						it receives.
						</para>
						</enum>
						<enum name="out">
						<para>
						Asterisk will only receive media from the application, but will
						not send any media.
						</para>
						</enum>
						</enumlist>
					</enum>
					<enum name="f(format) - Control message format for this call">
						<para>
						format:
						</para>
						<xi:include xpointer="xpointer(/docs/configInfo[@name='chan_websocket']/configFile[@name='chan_websocket.conf']/configObject[@name='global']/configOption[@name='control_message_format']/description/enumlist)"/>
					</enum>
					<enum name="n - Don't auto answer">
						<para>Normally, the WebSocket channel will be answered when
						connection is established with the remote app.  If this
						option is specified however, the channel will not be
						answered until the <literal>ANSWER</literal> command is
						received from the remote app or the remote app calls the
						/channels/answer ARI endpoint.
						</para>
					</enum>
					<enum name="p - Passthrough mode">
						<para>In passthrough mode, the channel driver won't attempt
						to re-frame or re-time media coming in over the websocket from
						the remote app.  This can be used for any codec but MUST be used
						for codecs that use packet headers or whose data stream can't be
						broken up on arbitrary byte boundaries. In this case, the remote
						app is fully responsible for correctly framing and timing media
						sent to Asterisk and the MEDIA text commands that could be sent
						over the websocket are disabled.  Currently, passthrough mode is
						automatically set for the opus, speex and g729 codecs.
						</para>
					</enum>
					<enum name="u - Unbuffered mode">
						<para>In unbuffered mode, the channel driver won't attempt
						to re-frame or re-time media coming in over the websocket from
						the remote app. In this case, the remote app is fully responsible
						for correctly framing and timing media sent to Asterisk.  This is
						useful for when the app is getting its media from a source that's
						already framed and timed. The difference between unbuffered and
						passthrough modes is that, if you're not using an unbufferable
						codec (opus, speex and g729), you can still use START_MEDIA_BUFFERING
						to switch to buffered mode to send a file, then when you call
						STOP_MEDIA_BUFFERING, the channel will go back into unbuffered
						mode.
						</para>
					</enum>
					<enum name="v(uri_parameters) - Add parameters to the outbound URI">
						<para>This option allows you to add additional parameters to the
						outbound URI.  The format is:
						<literal>v(param1=value1,param2=value2...)</literal>
						</para>
						<para>You must ensure that no parameter name or value contains
						characters not valid in a URL.  The easiest way to do this is to
						use the URIENCODE() dialplan function to encode them.  Be aware
						though that each name and value must be encoded separately.  You
						can't simply encode the whole string.</para>
					</enum>
				</enumlist>
			</enum>
		</enumlist>
		<para>Examples:
		</para>
		<example title="Make an outbound WebSocket connection using connection 'connection1' and the 'sln16' codec.">
		same => n,Dial(WebSocket/connection1/c(sln16))
		</example>
		<example title="Make an outbound WebSocket connection using connection 'connection1' and the 'opus' codec. Passthrough mode will automatically be set.">
		same => n,Dial(WebSocket/connection1/c(opus))
		</example>
		<example title="Listen for an incoming WebSocket connection and don't auto-answer it.">
		same => n,Dial(WebSocket/INCOMING/n)
		</example>
		<example title="Add URI parameters.">
		same => n,Dial(WebSocket/connection1/v(${URIENCODE(vari able)}=${URIENCODE(${CHANNEL})},variable2=$(URIENCODE(${EXTEN})}))
		</example>
		<example title="Use the JSON control message format for this call.">
		same => n,Dial(WebSocket/connection1/f(json))
		</example>
	</info>
</docs>
